# Generated by Django 3.1 on 2020-08-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywordfinder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Url',
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordfinder.url')),
            ],
            options={
                'verbose_name_plural': 'Keywords',
            },
        ),
    ]
