# Generated by Django 3.1 on 2020-08-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordfinder', '0002_auto_20200823_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='keyword',
        ),
    ]
