# Generated by Django 3.1 on 2020-08-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordfinder', '0003_remove_url_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='keyword',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
